name: CI

on: [push, pull_request]

jobs:
  build:

    timeout-minutes: 360
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        yocto-version: [main]
        machine: [qemuarm64, qemux86-64]
    steps:
    - name: Setup unpriviledged user namespaces
      # https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890
      run: |
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: Reclaim the bytes
      uses: data-intuitive/reclaim-the-bytes@v2
      with:
        remove-hosted-tool-cache: true
        remove-go: true
        remove-codeql: true
        remove-powershell: true
        remove-android-sdk: true
        remove-haskell-ghc: true
        remove-swift: true
        remove-dotnet: true
        remove-docker-images: true
        remove-swap: false
    - name: Install dependencies
      run: |
        sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 python3-subunit python3-websockets zstd liblz4-tool file locales libacl1
        sudo locale-gen en_US.UTF-8
        df -h
    - uses: actions/checkout@v1
    - name: Install Kas
      run: |
        sudo pip3 install kas

    - name: Restore sstate cache
      id: cache-sstate-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          sstate
        key: sstate-${{ matrix.yocto-version }}-${{ matrix.machine }}
        restore-keys: |
          sstate-${{ matrix.yocto-version }}
          sstate-
    - name: Move sstate
      run: |
        mkdir -p sstate
        mv sstate sstate-cache

    - name: Run kas on ${{ matrix.machine }} on ${{ matrix.yocto-version }}
      run: |
        export SSTATE_DIR="${PWD}/sstate"
        export SSTATE_MIRRORS="file://.* file://${PWD}/sstate-cache/PATH;downloadfilename=PATH"
        kas build kas/homeassistant-${{ matrix.yocto-version }}.yml:kas/machine-${{ matrix.machine }}.yml:kas/ci.yml

    - name: Save sstate cache
      id: cache-sstate-save
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          sstate
        key: ${{ steps.cache-sstate-restore.outputs.cache-primary-key }}
